{
 "title": "Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Cars dispatched",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByTags(nonNegativeDerivative(groupByTags(seriesByTag('kind=car'), 'sumSeries', 'color')), 'color')"
    }
   ]
  },
  {
   "title": "Cows dispatched",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "aliasByTags(nonNegativeDerivative(groupByTags(seriesByTag('kind=cow'), 'sumSeries', 'color')), 'color')"
    }
   ]
  },
  {
   "title": "Escapes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "aliasByTags(nonNegativeDerivative(groupByTags(seriesByTag('name=escapes'), 'sum', 'kind')), 'kind')"
    }
   ]
  },
  {
   "title": "Cows hit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "aliasByTags(nonNegativeDerivative(groupByTags(seriesByTag('name=hits', 'kind=cow'), 'sumSeries', 'color')), 'color')"
    }
   ]
  }
 ]
}